### ISSUE TITLE
Not sure why this happens

### ISSUE THREAD

**Issue by davidascher** [anacronw/js-fixtures#18]
Using karma + sinon-chai with what I think are appropriate config parameters:

```
        chai.should();
        fixtures.path = 'base';
        console.log('read');
        body = fixtures.read('index2.html');
        console.log('set');
        fixtures.set(body);
        $$ = document.getElementById(fixtures.containerId).contentDocument.documentElement;
        console.log("CONTENT", $$);
        console.log('load');
        fixtures.load('index2.html');
        console.log('loaded');
        $$ = document.getElementById(fixtures.containerId).contentDocument.documentElement;
        console.log("AGAIN", $$);

```

is yielding:

```
LOG: 'read'
LOG: 'set'
LOG: 'CONTENT', <html><head><link rel="import" href="https://appmaker.mozillalabs.com/test_assets/ceci/ceci-broadcast.html">
    <link rel="import" href="https://appmaker.mozillalabs.com/test_assets/ceci/ceci-listen.html">
    <link rel="import" href="https://appmaker.mozillalabs.com/test_assets/ceci/ceci-element.html">
    <link rel="import" href="https://appmaker.mozillalabs.com/test_assets/ceci/ceci-app.html">
    <link rel="import" href="https://appmaker.mozillalabs.com/test_assets/ceci/ceci-card.html">
    <link rel="import" href="https://appmaker.mozillalabs.com/test_assets/ceci/test/fixtures/ceci-value-holder.html">

    <!-- The component we're testing here. -->
    <link rel="import" href="component.html">

    <script src="https://appmaker.mozillalabs.com/test_assets/vendor/polymer/polymer.min.js"></script></head></html>
LOG: 'load'
Chrome 33.0.1713 (Mac OS X 10.9.0) button "before each" hook FAILED
    TypeError: Cannot read property 'innerHTML' of null
        at addToContainer (/Users/davida/src/mozilla-appmaker/component-button/fixtures.js:91:44)
        at self.load (/Users/davida/src/mozilla-appmaker/component-button/fixtures.js:34:13)
        at Context.<anonymous> (/Users/davida/src/mozilla-appmaker/component-button/jasmine.js:17:15)
        at Hook.Runnable.run (/Users/davida/src/mozilla-appmaker/component-button/node_modules/mocha/mocha.js:4263:32)
        at next (/Users/davida/src/mozilla-appmaker/component-button/node_modules/mocha/mocha.js:4526:10)
        at /Users/davida/src/mozilla-appmaker/component-button/node_modules/mocha/mocha.js:4538:5
        at timeslice (/Users/davida/src/mozilla-appmaker/component-button/node_modules/mocha/mocha.js:5531:27)
Chrome 33.0.1713 (Mac OS X 10.9.0): Executed 1 of 1 (1 FAILED) ERROR (1.539 secs / NaN secs)

```

meaning that `set(read('index2.html'))` is working, but `load('index2.html')` is resulting in an exception.

Any idea?

**Comment by anacronw** [comment]
Yeah, I think I know why.  Recently, this was brought up here: https://github.com/badunk/js-fixtures/issues/15

I implemented the async load API for that specific case, but I realized a proper fix is to go through an entirely new approach.  Quick explanation is here: https://github.com/badunk/js-fixtures/issues/15#issuecomment-28055859.

Its interesting to me that set(read('index2.html')) works, however...

Does using set(read()) work for you in the meantime?

**Comment by davidascher** [comment]
Not sure yet.  A few things still aren't working but I'm not sure where the
fault lies.

in particular, with a fairly boring html doc (
https://gist.github.com/davidascher/7558740), when I ask for
`fixtures.window().document`, I get a document which has a head that seems
to includ multiple copies of the actual head contents, and no <body>.

I wonder if the assembly of chunks is somehow not working right.

Totally funny that @dmose filed the other issue (we're colleagues working
on non-overlapping projects ;-).

**Comment by anacronw** [comment]
The fixtures were originally only designed to load stuff into body actually.  The fact that it can load some scripts in head is a sorta byproduct.
