### ISSUE TITLE
Allow fixtures to define fixture area HTML node type

### ISSUE THREAD

**Issue by dualcyclone** [anacronw/js-fixtures#22]
I had a problem yesterday whereby my existing Jasmine-jQuery fixtures were not accessible to my tests; I discovered this was because they were loading inside the iframe.

I have modified the code to include a "type" (same method as with "path"), but I have also modified the other instances in the code that would expect an actual window/document instead of a normal HTML node.

This seems to work, I am unsure what the "cb" function is in the createContainer function, otherwise I'd like to be able to commit this.

The reason I have done this is because Karma is already configured to load the necessary resources I need, and I am writing tests for scripts that would normally be loaded in a normal webpage. My fixtures are very short HTML snippets, and are designed primarily to be copied into the same context as the included scripts (as with jasmine-jquery) - however we are moving away from Jasmine in favour of a more configurable Mocha framework - if you believe this request to be out of context or lacks reason, please respond!

**Comment by anacronw** [comment]
I see your use case, this issue keeps popping up here, however.

I am somewhat convinced that the default should act like jasmine-jquery inside a div sandbox, while purists would appreciate the iframe approach.  When I first developed this, I found the test runner itself to be conflicting with the test.

If you submit a PR, I'll be glad to take a look at it

**Comment by dualcyclone** [comment]
I've pulled down the latest code from the repository, but I'm getting an error on one of the tests. I have reverted all of my changes to see if it was something I have introduced, but the issue persists.

Slightly different stack-traces in Chrome and Firefox, but they both point at the same issue (this is the trace from Chrome):

Fixtures > load > when a callback is passed > executes when iframe is ready

TypeError: Object #<Object> has no method 'spyCall'
    at Function.getCall (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/node_modules/sinon/lib/sinon/spy.js:181:26)
    at Function.createCallProperties (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/node_modules/sinon/lib/sinon/spy.js:66:31)
    at Function.invoke (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/node_modules/sinon/lib/sinon/spy.js:167:34)
    at FakeXMLHttpRequest.proxy [as send](eval at createProxy %28file:///Users/lukedyson/Documents/GITHUB/js-fixtures/node_modules/sinon/lib/sinon/spy.js:77:82%29, <anonymous>:1:35)
    at loadFixtureIntoCache (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/fixtures.js:111:21)
    at getFixtureHtml (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/fixtures.js:103:17)
    at file:///Users/lukedyson/Documents/GITHUB/js-fixtures/fixtures.js:49:67
    at Array.forEach (native)
    at self.read (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/fixtures.js:48:54)
    at self.load (file:///Users/lukedyson/Documents/GITHUB/js-fixtures/fixtures.js:34:38)

I've installed the dependencies, are you seeing the same?

**Comment by anacronw** [comment]
ah interesting, after wiping my node_modules, it seems like its a problem introduced after getting the latest dependencies.  Give me a couple mins to figure this out.

Thanks

**Comment by anacronw** [comment]
Can you please pull again?  I don't know why, but when I started the project I had allowed breaking changes ">=" for dependencies.  That was stupid.  Fix is in 1.5.1

**Comment by dualcyclone** [comment]
Cool, done another pull and everything seems fixed. I'll apply my changes and see if it still works, might add a few tests too

**Comment by dualcyclone** [comment]
Sorry realised I haven't actually commented on this for some time; I haven't written the test to cover my work, but the existing tests still pass, do you still want me to check this in?

**Comment by anacronw** [comment]
sure, I'm interested in looking at it

Thanks

**Comment by anacronw** [comment]
Just to be sure, @dualcyclone will you be submitting a PR?
